import:
    title: Import Messages
    modelClass: RainLab\Translate\Models\MessageImport
    redirect: rainlab/translate/messages

export:
    title: Export Messages
    modelClass: RainLab\Translate\Models\MessageExport
    redirect: rainlab/translate/messages
